### ISSUE TITLE
que version de python utiliza ?

### ISSUE THREAD

**Issue by abelnexus** [jdeloshoyos/mailer#1]
me salen errores en estas lineas:
justo en los ´=´

`print('['+str(elem_actual)+'/'+str(total_elems)+'] Enviando: '+i[0], end=' ')`
`print('[ERROR]', end=' ')`

si las comento me salen mas errores:
UnicodeDecodeError: ´ascii´ codec can´t  decode byte in position 1304 : ordinal  not in range(128)

**Comment by jdeloshoyos** [comment]
Hola! El script funciona sobre Python 3, lo he usado desde 3.6 hasta 3.8 sin problemas. Estás usando Python 2 por casualidad?
Saludos,

**Comment by abelnexus** [comment]
logre que corra, pero solo me muestra las opciones y termina el programa

**Comment by abelnexus** [comment]
lo puse por default tanto el archivo lista.csv y correo.html, funciona perfecto amigo, tengo una duda en caso que algun correo me salga error como podria capturar el nombre o direccion de email que salio mal, por ejemplo en un archivo de texto poner el correo de todos los que no se enviaron

**Comment by jdeloshoyos** [comment]
> lo puse por default tanto el archivo lista.csv y correo.html, funciona perfecto amigo, tengo una duda en caso que algun correo me salga error como podria capturar el nombre o direccion de email que salio mal, por ejemplo en un archivo de texto poner el correo de todos los que no se enviaron

Eso es algo que he pensado implementar, sería muy fácil de hacer. Si quieres intentarlo, en el bloque "except" al final del programa se manejan los envíos erróneos. Ahí podrías ir agregando la información que te interese a una lista, para imprimirla o guardarla a un archivo de salida al terminar el proceso.
